/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.in.kafka.avro;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class Otp extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -8726228253399844739L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"Otp\",\"namespace\":\"com.in.kafka.avro\",\"fields\":[{\"name\":\"otp\",\"type\":\"string\"},{\"name\":\"email\",\"type\":\"string\"},{\"name\":\"failedAttempts\",\"type\":\"int\"},{\"name\":\"OtpType\",\"type\":\"string\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<Otp> ENCODER =
      new BinaryMessageEncoder<Otp>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<Otp> DECODER =
      new BinaryMessageDecoder<Otp>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<Otp> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<Otp> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<Otp> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<Otp>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this Otp to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a Otp from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a Otp instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static Otp fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  private java.lang.CharSequence otp;
  private java.lang.CharSequence email;
  private int failedAttempts;
  private java.lang.CharSequence OtpType;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public Otp() {}

  /**
   * All-args constructor.
   * @param otp The new value for otp
   * @param email The new value for email
   * @param failedAttempts The new value for failedAttempts
   * @param OtpType The new value for OtpType
   */
  public Otp(java.lang.CharSequence otp, java.lang.CharSequence email, java.lang.Integer failedAttempts, java.lang.CharSequence OtpType) {
    this.otp = otp;
    this.email = email;
    this.failedAttempts = failedAttempts;
    this.OtpType = OtpType;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return otp;
    case 1: return email;
    case 2: return failedAttempts;
    case 3: return OtpType;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: otp = (java.lang.CharSequence)value$; break;
    case 1: email = (java.lang.CharSequence)value$; break;
    case 2: failedAttempts = (java.lang.Integer)value$; break;
    case 3: OtpType = (java.lang.CharSequence)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'otp' field.
   * @return The value of the 'otp' field.
   */
  public java.lang.CharSequence getOtp() {
    return otp;
  }


  /**
   * Sets the value of the 'otp' field.
   * @param value the value to set.
   */
  public void setOtp(java.lang.CharSequence value) {
    this.otp = value;
  }

  /**
   * Gets the value of the 'email' field.
   * @return The value of the 'email' field.
   */
  public java.lang.CharSequence getEmail() {
    return email;
  }


  /**
   * Sets the value of the 'email' field.
   * @param value the value to set.
   */
  public void setEmail(java.lang.CharSequence value) {
    this.email = value;
  }

  /**
   * Gets the value of the 'failedAttempts' field.
   * @return The value of the 'failedAttempts' field.
   */
  public int getFailedAttempts() {
    return failedAttempts;
  }


  /**
   * Sets the value of the 'failedAttempts' field.
   * @param value the value to set.
   */
  public void setFailedAttempts(int value) {
    this.failedAttempts = value;
  }

  /**
   * Gets the value of the 'OtpType' field.
   * @return The value of the 'OtpType' field.
   */
  public java.lang.CharSequence getOtpType() {
    return OtpType;
  }


  /**
   * Sets the value of the 'OtpType' field.
   * @param value the value to set.
   */
  public void setOtpType(java.lang.CharSequence value) {
    this.OtpType = value;
  }

  /**
   * Creates a new Otp RecordBuilder.
   * @return A new Otp RecordBuilder
   */
  public static com.in.kafka.avro.Otp.Builder newBuilder() {
    return new com.in.kafka.avro.Otp.Builder();
  }

  /**
   * Creates a new Otp RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new Otp RecordBuilder
   */
  public static com.in.kafka.avro.Otp.Builder newBuilder(com.in.kafka.avro.Otp.Builder other) {
    if (other == null) {
      return new com.in.kafka.avro.Otp.Builder();
    } else {
      return new com.in.kafka.avro.Otp.Builder(other);
    }
  }

  /**
   * Creates a new Otp RecordBuilder by copying an existing Otp instance.
   * @param other The existing instance to copy.
   * @return A new Otp RecordBuilder
   */
  public static com.in.kafka.avro.Otp.Builder newBuilder(com.in.kafka.avro.Otp other) {
    if (other == null) {
      return new com.in.kafka.avro.Otp.Builder();
    } else {
      return new com.in.kafka.avro.Otp.Builder(other);
    }
  }

  /**
   * RecordBuilder for Otp instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<Otp>
    implements org.apache.avro.data.RecordBuilder<Otp> {

    private java.lang.CharSequence otp;
    private java.lang.CharSequence email;
    private int failedAttempts;
    private java.lang.CharSequence OtpType;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.in.kafka.avro.Otp.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.otp)) {
        this.otp = data().deepCopy(fields()[0].schema(), other.otp);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.email)) {
        this.email = data().deepCopy(fields()[1].schema(), other.email);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.failedAttempts)) {
        this.failedAttempts = data().deepCopy(fields()[2].schema(), other.failedAttempts);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (isValidValue(fields()[3], other.OtpType)) {
        this.OtpType = data().deepCopy(fields()[3].schema(), other.OtpType);
        fieldSetFlags()[3] = other.fieldSetFlags()[3];
      }
    }

    /**
     * Creates a Builder by copying an existing Otp instance
     * @param other The existing instance to copy.
     */
    private Builder(com.in.kafka.avro.Otp other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.otp)) {
        this.otp = data().deepCopy(fields()[0].schema(), other.otp);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.email)) {
        this.email = data().deepCopy(fields()[1].schema(), other.email);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.failedAttempts)) {
        this.failedAttempts = data().deepCopy(fields()[2].schema(), other.failedAttempts);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.OtpType)) {
        this.OtpType = data().deepCopy(fields()[3].schema(), other.OtpType);
        fieldSetFlags()[3] = true;
      }
    }

    /**
      * Gets the value of the 'otp' field.
      * @return The value.
      */
    public java.lang.CharSequence getOtp() {
      return otp;
    }


    /**
      * Sets the value of the 'otp' field.
      * @param value The value of 'otp'.
      * @return This builder.
      */
    public com.in.kafka.avro.Otp.Builder setOtp(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.otp = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'otp' field has been set.
      * @return True if the 'otp' field has been set, false otherwise.
      */
    public boolean hasOtp() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'otp' field.
      * @return This builder.
      */
    public com.in.kafka.avro.Otp.Builder clearOtp() {
      otp = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'email' field.
      * @return The value.
      */
    public java.lang.CharSequence getEmail() {
      return email;
    }


    /**
      * Sets the value of the 'email' field.
      * @param value The value of 'email'.
      * @return This builder.
      */
    public com.in.kafka.avro.Otp.Builder setEmail(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.email = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'email' field has been set.
      * @return True if the 'email' field has been set, false otherwise.
      */
    public boolean hasEmail() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'email' field.
      * @return This builder.
      */
    public com.in.kafka.avro.Otp.Builder clearEmail() {
      email = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'failedAttempts' field.
      * @return The value.
      */
    public int getFailedAttempts() {
      return failedAttempts;
    }


    /**
      * Sets the value of the 'failedAttempts' field.
      * @param value The value of 'failedAttempts'.
      * @return This builder.
      */
    public com.in.kafka.avro.Otp.Builder setFailedAttempts(int value) {
      validate(fields()[2], value);
      this.failedAttempts = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'failedAttempts' field has been set.
      * @return True if the 'failedAttempts' field has been set, false otherwise.
      */
    public boolean hasFailedAttempts() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'failedAttempts' field.
      * @return This builder.
      */
    public com.in.kafka.avro.Otp.Builder clearFailedAttempts() {
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'OtpType' field.
      * @return The value.
      */
    public java.lang.CharSequence getOtpType() {
      return OtpType;
    }


    /**
      * Sets the value of the 'OtpType' field.
      * @param value The value of 'OtpType'.
      * @return This builder.
      */
    public com.in.kafka.avro.Otp.Builder setOtpType(java.lang.CharSequence value) {
      validate(fields()[3], value);
      this.OtpType = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'OtpType' field has been set.
      * @return True if the 'OtpType' field has been set, false otherwise.
      */
    public boolean hasOtpType() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'OtpType' field.
      * @return This builder.
      */
    public com.in.kafka.avro.Otp.Builder clearOtpType() {
      OtpType = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public Otp build() {
      try {
        Otp record = new Otp();
        record.otp = fieldSetFlags()[0] ? this.otp : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.email = fieldSetFlags()[1] ? this.email : (java.lang.CharSequence) defaultValue(fields()[1]);
        record.failedAttempts = fieldSetFlags()[2] ? this.failedAttempts : (java.lang.Integer) defaultValue(fields()[2]);
        record.OtpType = fieldSetFlags()[3] ? this.OtpType : (java.lang.CharSequence) defaultValue(fields()[3]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<Otp>
    WRITER$ = (org.apache.avro.io.DatumWriter<Otp>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<Otp>
    READER$ = (org.apache.avro.io.DatumReader<Otp>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeString(this.otp);

    out.writeString(this.email);

    out.writeInt(this.failedAttempts);

    out.writeString(this.OtpType);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.otp = in.readString(this.otp instanceof Utf8 ? (Utf8)this.otp : null);

      this.email = in.readString(this.email instanceof Utf8 ? (Utf8)this.email : null);

      this.failedAttempts = in.readInt();

      this.OtpType = in.readString(this.OtpType instanceof Utf8 ? (Utf8)this.OtpType : null);

    } else {
      for (int i = 0; i < 4; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.otp = in.readString(this.otp instanceof Utf8 ? (Utf8)this.otp : null);
          break;

        case 1:
          this.email = in.readString(this.email instanceof Utf8 ? (Utf8)this.email : null);
          break;

        case 2:
          this.failedAttempts = in.readInt();
          break;

        case 3:
          this.OtpType = in.readString(this.OtpType instanceof Utf8 ? (Utf8)this.OtpType : null);
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










