/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.in.kafka.avro;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class RecentlyViewedHistory extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 6202900883154843789L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"RecentlyViewedHistory\",\"namespace\":\"com.in.kafka.avro\",\"fields\":[{\"name\":\"productIds\",\"type\":{\"type\":\"array\",\"items\":{\"type\":\"string\",\"avro.java.string\":\"String\"}}}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<RecentlyViewedHistory> ENCODER =
      new BinaryMessageEncoder<RecentlyViewedHistory>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<RecentlyViewedHistory> DECODER =
      new BinaryMessageDecoder<RecentlyViewedHistory>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<RecentlyViewedHistory> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<RecentlyViewedHistory> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<RecentlyViewedHistory> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<RecentlyViewedHistory>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this RecentlyViewedHistory to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a RecentlyViewedHistory from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a RecentlyViewedHistory instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static RecentlyViewedHistory fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  private java.util.List<java.lang.String> productIds;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public RecentlyViewedHistory() {}

  /**
   * All-args constructor.
   * @param productIds The new value for productIds
   */
  public RecentlyViewedHistory(java.util.List<java.lang.String> productIds) {
    this.productIds = productIds;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return productIds;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: productIds = (java.util.List<java.lang.String>)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'productIds' field.
   * @return The value of the 'productIds' field.
   */
  public java.util.List<java.lang.String> getProductIds() {
    return productIds;
  }


  /**
   * Sets the value of the 'productIds' field.
   * @param value the value to set.
   */
  public void setProductIds(java.util.List<java.lang.String> value) {
    this.productIds = value;
  }

  /**
   * Creates a new RecentlyViewedHistory RecordBuilder.
   * @return A new RecentlyViewedHistory RecordBuilder
   */
  public static com.in.kafka.avro.RecentlyViewedHistory.Builder newBuilder() {
    return new com.in.kafka.avro.RecentlyViewedHistory.Builder();
  }

  /**
   * Creates a new RecentlyViewedHistory RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new RecentlyViewedHistory RecordBuilder
   */
  public static com.in.kafka.avro.RecentlyViewedHistory.Builder newBuilder(com.in.kafka.avro.RecentlyViewedHistory.Builder other) {
    if (other == null) {
      return new com.in.kafka.avro.RecentlyViewedHistory.Builder();
    } else {
      return new com.in.kafka.avro.RecentlyViewedHistory.Builder(other);
    }
  }

  /**
   * Creates a new RecentlyViewedHistory RecordBuilder by copying an existing RecentlyViewedHistory instance.
   * @param other The existing instance to copy.
   * @return A new RecentlyViewedHistory RecordBuilder
   */
  public static com.in.kafka.avro.RecentlyViewedHistory.Builder newBuilder(com.in.kafka.avro.RecentlyViewedHistory other) {
    if (other == null) {
      return new com.in.kafka.avro.RecentlyViewedHistory.Builder();
    } else {
      return new com.in.kafka.avro.RecentlyViewedHistory.Builder(other);
    }
  }

  /**
   * RecordBuilder for RecentlyViewedHistory instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<RecentlyViewedHistory>
    implements org.apache.avro.data.RecordBuilder<RecentlyViewedHistory> {

    private java.util.List<java.lang.String> productIds;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.in.kafka.avro.RecentlyViewedHistory.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.productIds)) {
        this.productIds = data().deepCopy(fields()[0].schema(), other.productIds);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
    }

    /**
     * Creates a Builder by copying an existing RecentlyViewedHistory instance
     * @param other The existing instance to copy.
     */
    private Builder(com.in.kafka.avro.RecentlyViewedHistory other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.productIds)) {
        this.productIds = data().deepCopy(fields()[0].schema(), other.productIds);
        fieldSetFlags()[0] = true;
      }
    }

    /**
      * Gets the value of the 'productIds' field.
      * @return The value.
      */
    public java.util.List<java.lang.String> getProductIds() {
      return productIds;
    }


    /**
      * Sets the value of the 'productIds' field.
      * @param value The value of 'productIds'.
      * @return This builder.
      */
    public com.in.kafka.avro.RecentlyViewedHistory.Builder setProductIds(java.util.List<java.lang.String> value) {
      validate(fields()[0], value);
      this.productIds = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'productIds' field has been set.
      * @return True if the 'productIds' field has been set, false otherwise.
      */
    public boolean hasProductIds() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'productIds' field.
      * @return This builder.
      */
    public com.in.kafka.avro.RecentlyViewedHistory.Builder clearProductIds() {
      productIds = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public RecentlyViewedHistory build() {
      try {
        RecentlyViewedHistory record = new RecentlyViewedHistory();
        record.productIds = fieldSetFlags()[0] ? this.productIds : (java.util.List<java.lang.String>) defaultValue(fields()[0]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<RecentlyViewedHistory>
    WRITER$ = (org.apache.avro.io.DatumWriter<RecentlyViewedHistory>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<RecentlyViewedHistory>
    READER$ = (org.apache.avro.io.DatumReader<RecentlyViewedHistory>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    long size0 = this.productIds.size();
    out.writeArrayStart();
    out.setItemCount(size0);
    long actualSize0 = 0;
    for (java.lang.String e0: this.productIds) {
      actualSize0++;
      out.startItem();
      out.writeString(e0);
    }
    out.writeArrayEnd();
    if (actualSize0 != size0)
      throw new java.util.ConcurrentModificationException("Array-size written was " + size0 + ", but element count was " + actualSize0 + ".");

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      long size0 = in.readArrayStart();
      java.util.List<java.lang.String> a0 = this.productIds;
      if (a0 == null) {
        a0 = new SpecificData.Array<java.lang.String>((int)size0, SCHEMA$.getField("productIds").schema());
        this.productIds = a0;
      } else a0.clear();
      SpecificData.Array<java.lang.String> ga0 = (a0 instanceof SpecificData.Array ? (SpecificData.Array<java.lang.String>)a0 : null);
      for ( ; 0 < size0; size0 = in.arrayNext()) {
        for ( ; size0 != 0; size0--) {
          java.lang.String e0 = (ga0 != null ? ga0.peek() : null);
          e0 = in.readString();
          a0.add(e0);
        }
      }

    } else {
      for (int i = 0; i < 1; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          long size0 = in.readArrayStart();
          java.util.List<java.lang.String> a0 = this.productIds;
          if (a0 == null) {
            a0 = new SpecificData.Array<java.lang.String>((int)size0, SCHEMA$.getField("productIds").schema());
            this.productIds = a0;
          } else a0.clear();
          SpecificData.Array<java.lang.String> ga0 = (a0 instanceof SpecificData.Array ? (SpecificData.Array<java.lang.String>)a0 : null);
          for ( ; 0 < size0; size0 = in.arrayNext()) {
            for ( ; size0 != 0; size0--) {
              java.lang.String e0 = (ga0 != null ? ga0.peek() : null);
              e0 = in.readString();
              a0.add(e0);
            }
          }
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










